steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=us-central1-docker.pkg.dev/pure-coda-368223/python-app/pyjokes:latest
      - --file=./Dockerfile
      - .
images:
  - us-central1-docker.pkg.dev/pure-coda-368223/python-app/pyjokes:latest
